version: 1
metadata:
  authors: Érico Perez Neto
external_links:
  documentation: https://github.com/ericodx/swift-mutation-testing/blob/main/Docs/USAGE.MD
builder:
  configs:
    - platform: macos-spm
      swift_version: "6.4"
    - platform: macos-spm
      swift_version: "6.3"
    - platform: macos-spm
      swift_version: "6.2"
